export const listCategoriesPhrases = [
    'show me all categories',
    'get all categories',
    'list all product categories',
    'display all categories',
    'list product categories',
    'give me all categories',
    'categories list',
    'fetch all categories',
    'show categories',
    'list down categories',
    'can you show all categories',
    'what are the available categories',
    'get a list of categories',
    'list every category',
    'please display all categories',
    'find all categories',
    'give the categories list',
    'fetch product categories',
    'I need a list of categories',
    'retrieve all categories',
    'can I see all categories',
    'show all product categories',
    'list available categories',
    'give me product categories',
    'categories available',
    'categories list please',
    'get a list of all categories',
    'fetch a list of categories',
    'list out all categories',
    'what categories do you have',
    'give me the product categories list',
    'show me the list of categories',
    'can you get all categories',
    'list of all categories',
    'product categories list',
    'list out product categories',
    'display a list of categories',
    'show available categories',
    'tell me all categories',
    'get categories list',
    'list the categories',
    'give the product categories',
    'I want the categories list',
    'fetch me the categories',
    'list all the categories you have',
    'what are the categories',
    'show the product categories',
    'list all your categories',
    'can I have a categories list',
    'get me product categories',
    'show categories available',
    'please list all categories',
    'provide a list of categories',
    'give details of all categories',
    'can you display categories',
    'list all kinds of categories',
    'fetch me the product categories',
    'can you provide the categories',
    'I need the categories available',
    'categories, please list them',
    'what product categories are there',
    'categories, show them to me',
    'show me categories available now',
    'fetch all the product categories',
    'display categories available',
    'list categories right now',
    'can you list categories for me',
    'please give me the categories list',
    'fetch a list of product categories',
    'give the complete categories list',
    'list down all available categories',
    'list every product category here',
    'I need product categories now',
    'show every category you have',
    'can I see the categories list',
    'categories, what do you have',
    'provide all product categories',
    'list the categories you offer',
    'give me the full list of categories',
    'fetch all the categories you have',
    'tell me all product categories',
    'show the list of product categories',
    'can you fetch all categories',
    'list down the product categories',
    'what categories can you show',
    'list categories as soon as possible',
    'show every product category',
    'list all categories present',
    'categories, show them all',
    'get me all product categories',
    'give all the categories available',
    'fetch all kinds of categories',
    'show categories from your system',
    'list every available category',
    'can you display the categories list',
    'I want to see the categories list',
    'give me all your product categories',
    'fetch me the list of categories',
    'categories, I need them listed',
    'show every single category here',
    'list down the available categories',
    'give me every product category',
    'categories, display them all',
    'what categories do you list',
    'show me the complete categories list',
    'list product categories available',
    'categories, fetch them all now',
    'get me the available product categories',
    'list out the categories for me',
    'tell me about all categories',
    'show all categories instantly',
    'please display product categories',
    'list the product categories available',
    'get the list of all product categories',
    'categories list, display it now',
    'can you show the product categories',
    'list every available product category'
]


export const productDetailPhrases = [
    'show me all products',
    'list all products',
    'get all products',
    'display all products',
    'fetch all products',
    'show all items',
    'list all items',
    'give me a list of products',
    'what products are available',
    'show all available products',
    'can you display all products',
    'I want to see all products',
    'list every product',
    'retrieve all products',
    'show me the product list',
    'give me all available products',
    'list down all products',
    'fetch the product list',
    'can you show me the products',
    'list all the products',
    'list out all products',
    'what are the available products',
    'show me the list of products',
    'display available products',
    'what items do you have',
    'give me all items',
    'fetch all the items',
    'I want all product details',
    'show all the products in stock',
    'list products in inventory',
    'can you show me the items',
    'list all the available products',
    'display every product',
    'give me a list of available products',
    'show all inventory products',
    'retrieve all items',
    'can you list all the products',
    'what products are in stock',
    'show me your products',
    'list everything available',
    'fetch me all the products',
    'I need all products',
    'display all available items',
    'list every item',
    'retrieve product list',
    'show me product details',
    'what products do you have',
    'give me products list',
    'list all your products',
    'display all the products you have',
    'can I see all products',
    'show all product details',
    'fetch product list',
    'I want the product list',
    'list every product in stock',
    'display all the items',
    'retrieve all the products',
    'what are your products',
    'show me the inventory list',
    'list out your products',
    'give me details of all products',
    'show every item',
    'list all products available',
    'fetch all products in inventory',
    'show all available items',
    'retrieve details of products',
    'show all items in stock',
    'list all products you have',
    'can I see the product list',
    'what is the list of products',
    'show the products available',
    'fetch all the available products',
    'display every item in stock',
    'list down your products',
    'can you show all items',
    'give me all the product details',
    'list products in stock',
    'show every product available',
    'fetch the available products',
    'display the product inventory',
    'list all the products in inventory',
    'show the available products',
    'what items are in inventory',
    'retrieve all available products',
    'list the entire inventory',
    'display all stock products',
    'what are the products you have',
    'can you give me the product list',
    'show all products and details',
    'list all products and items',
    'retrieve the inventory list',
    'fetch products in stock',
    'list every product available',
    'show me the inventory',
    'list the products and details',
    'fetch me the inventory products',
    'what products can I see',
    'give me the inventory list'
  ];


  export const getProductDetailPhrases = [
    'show me details of the product',
    'get details of a product',
    'show product details',
    'fetch product details',
    'give me the product details',
    'I want details of a product',
    'show details for a specific product',
    'get information about a product',
    'can you show details of the product',
    'fetch details for a product',
    'give me details of the product',
    'display product details',
    'I need details of a product',
    'show me the product information',
    'provide details of a product',
    'get product details by name',
    'show me the details for this product',
    'fetch me the product details',
    'retrieve product information',
    'give information about the product',
    'show the details for this product',
    'find details for a product',
    'show me the product description',
    'get product details by ID',
    'what are the details of this product',
    'display details for a product',
    'give details of the selected product',
    'show the product specification',
    'fetch the product description',
    'show the details for a specific product',
    'retrieve details of a product',
    'get details of a specific product',
    'can I get the product details',
    'find information about this product',
    'I need the product information',
    'can you get details of this product',
    'list details for the product',
    'give me the product specification',
    'show me the information for a product',
    'get the details of the selected product',
    'fetch the product info',
    'give me product details for this item',
    'what is the specification of the product',
    'get me the product details',
    'can you fetch product details',
    'display the product information',
    'what are the product specifications',
    'retrieve details for the product',
    'find product description',
    'show the product information',
    'give me product specifications',
    'I want product details for this item',
    'get the description of a product',
    'show the product name and details',
    'fetch product specifications',
    'what is the information about this product',
    'retrieve the details for a specific product',
    'find specifications for this product',
    'show product details for this item',
    'get detailed information about the product',
    'give me details about a specific product',
    'find product details by ID',
    'show me details of a specific item',
    'what are the details for the product',
    'display product specifications',
    'give me the details for this item',
    'fetch information for a specific product',
    'retrieve the product description',
    'can you show me details for a product',
    'I need detailed info about the product',
    'show me specifications for this product',
    'what is the info about the product',
    'list the product details',
    'give me the product name and details',
    'can I get product information',
    'show me detailed information about a product',
    'retrieve specifications for a product',
    'find the details of the selected product',
    'what is the product description',
    'fetch the detailed info for this product',
    'show me information about this product',
    'list details of a specific product',
    'get the details of this product',
    'show the product description and specifications',
    'can you retrieve product information',
    'give the product details and specifications',
    'what is the detailed info for this item',
    'get the information about this item',
    'fetch the details of the specific product',
    'show the specification for this product',
    'retrieve the description for this item',
    'list specifications for this product',
    'get the detailed description for this product',
    'what are the details for this item',
    'give me all the info about this product',
    'fetch detailed product specifications',
    'show detailed product description',
    'can I see product details by name',
    'what is the product info',
    'get the specific product details'
  ];
  
  