export const greet = [
    "Hii",
    "hi",
    "Hello",
    "Hey",
    "Good morning",
    "Good evening",
    "How are you?",
    "Hi there",
    "Hello there"
  ]

export const listCategoriesPhrases = [
  "category list",
  "show me all categories",
  "list of categories",
  "list all categories",
  "list of all categories",
  "get all categories",
  "list all product categories",
  "display all categories",
  "list product categories",
  "give me all categories",
  "give me the all category",
  "show category",
  "all category list",
  "categories list",
  "fetch all categories",
  "show categories",
  "list down categories",
  "can you show all categories",
  "what are the available categories",
  "get a list of categories",
  "list every category",
  "please display all categories",
  "find all categories",
  "give the categories list",
  "fetch product categories",
  "I need a list of categories",
  "retrieve all categories",
  "can I see all categories",
  "show all product categories",
  "list available categories",
  "give me product categories",
  "categories available",
  "categories list please",
  "get a list of all categories",
  "fetch a list of categories",
  "list out all categories",
  "what categories do you have",
  "give me the product categories list",
  "show me the list of categories",
  "can you get all categories",
  "list of all categories",
  "product categories list",
  "list out product categories",
  "display a list of categories",
  "show available categories",
  "tell me all categories",
  "get categories list",
  "list the categories",
  "give the product categories",
  "I want the categories list",
  "fetch me the categories",
  "list all the categories you have",
  "what are the categories",
  "show the product categories",
  "list all your categories",
  "can I have a categories list",
  "get me product categories",
  "show categories available",
  "please list all categories",
  "provide a list of categories",
  "give details of all categories",
  "can you display categories",
  "list all kinds of categories",
  "fetch me the product categories",
  "can you provide the categories",
  "I need the categories available",
  "categories, please list them",
  "what product categories are there",
  "categories, show them to me",
  "show me categories available now",
  "fetch all the product categories",
  "display categories available",
  "list categories right now",
  "can you list categories for me",
  "please give me the categories list",
  "fetch a list of product categories",
  "give the complete categories list",
  "list down all available categories",
  "list every product category here",
  "I need product categories now",
  "show every category you have",
  "can I see the categories list",
  "categories, what do you have",
  "provide all product categories",
  "list the categories you offer",
  "give me the full list of categories",
  "fetch all the categories you have",
  "tell me all product categories",
  "show the list of product categories",
  "can you fetch all categories",
  "list down the product categories",
  "what categories can you show",
  "list categories as soon as possible",
  "show every product category",
  "list all categories present",
  "categories, show them all",
  "get me all product categories",
  "give all the categories available",
  "fetch all kinds of categories",
  "show categories from your system",
  "list every available category",
  "can you display the categories list",
  "I want to see the categories list",
  "give me all your product categories",
  "fetch me the list of categories",
  "categories, I need them listed",
  "show every single category here",
  "list down the available categories",
  "give me every product category",
  "categories, display them all",
  "what categories do you list",
  "show me the complete categories list",
  "list product categories available",
  "categories, fetch them all now",
  "get me the available product categories",
  "list out the categories for me",
  "tell me about all categories",
  "show all categories instantly",
  "please display product categories",
  "list the product categories available",
  "get the list of all product categories",
  "categories list, display it now",
  "can you show the product categories",
  "list every available product category",
];

export const productDetailPhrases = [
  "products list",
  "list of all products",
  "list of products",
  "show me all products",
  "list all products",
  "get all products",
  "display all products",
  "fetch all products",
  "show all items",
  "list all items",
  "give me a list of products",
  "what products are available",
  "show all available products",
  "can you display all products",
  "I want to see all products",
  "list every product",
  "retrieve all products",
  "show me the product list",
  "give me all available products",
  "list down all products",
  "fetch the product list",
  "can you show me the products",
  "list all the products",
  "list out all products",
  "what are the available products",
  "show me the list of products",
  "display available products",
  "what items do you have",
  "give me all items",
  "fetch all the items",
  "I want all product details",
  "show all the products in stock",
  "list products in inventory",
  "can you show me the items",
  "list all the available products",
  "display every product",
  "give me a list of available products",
  "show all inventory products",
  "retrieve all items",
  "can you list all the products",
  "what products are in stock",
  "show me your products",
  "list everything available",
  "fetch me all the products",
  "I need all products",
  "display all available items",
  "list every item",
  "retrieve product list",
  "show me product details",
  "what products do you have",
  "give me products list",
  "list all your products",
  "display all the products you have",
  "can I see all products",
  "show all product details",
  "fetch product list",
  "I want the product list",
  "list every product in stock",
  "display all the items",
  "retrieve all the products",
  "what are your products",
  "show me the inventory list",
  "list out your products",
  "give me details of all products",
  "show every item",
  "list all products available",
  "fetch all products in inventory",
  "show all available items",
  "retrieve details of products",
  "show all items in stock",
  "list all products you have",
  "can I see the product list",
  "what is the list of products",
  "show the products available",
  "fetch all the available products",
  "display every item in stock",
  "list down your products",
  "can you show all items",
  "give me all the product details",
  "list products in stock",
  "show every product available",
  "fetch the available products",
  "display the product inventory",
  "list all the products in inventory",
  "show the available products",
  "what items are in inventory",
  "retrieve all available products",
  "list the entire inventory",
  "display all stock products",
  "what are the products you have",
  "can you give me the product list",
  "show all products and details",
  "list all products and items",
  "retrieve the inventory list",
  "fetch products in stock",
  "list every product available",
  "show me the inventory",
  "list the products and details",
  "fetch me the inventory products",
  "what products can I see",
  "give me the inventory list",
];

export const getSingleProductDetail = [
  "show me details of the product",
  "get details of a product",
  "show product details",
  "fetch product details",
  "give me the product details",
  "I want details of a product",
  "show details for a specific product",
  "get information about a product",
  "can you show details of the product",
  "fetch details for a product",
  "give me details of the product",
  "display product details",
  "I need details of a product",
  "show me the product information",
  "provide details of a product",
  "get product details by name",
  "show me the details for this product",
  "fetch me the product details",
  "retrieve product information",
  "give information about the product",
  "show the details for this product",
  "find details for a product",
  "show me the product description",
  "get product details by ID",
  "what are the details of this product",
  "display details for a product",
  "give details of the selected product",
  "show the product specification",
  "fetch the product description",
  "show the details for a specific product",
  "retrieve details of a product",
  "get details of a specific product",
  "can I get the product details",
  "find information about this product",
  "I need the product information",
  "can you get details of this product",
  "list details for the product",
  "give me the product specification",
  "show me the information for a product",
  "get the details of the selected product",
  "fetch the product info",
  "give me product details for this item",
  "what is the specification of the product",
  "get me the product details",
  "can you fetch product details",
  "display the product information",
  "what are the product specifications",
  "retrieve details for the product",
  "find product description",
  "show the product information",
  "give me product specifications",
  "I want product details for this item",
  "get the description of a product",
  "show the product details",
  "fetch product specifications",
  "what is the information about this product",
  "retrieve the details for a specific product",
  "find specifications for this product",
  "show product details for this item",
  "get detailed information about the product",
  "give me details about a specific product",
  "find product details by ID",
  "show me details of a specific item",
  "what are the details for the product",
  "display product specifications",
  "give me the details for this item",
  "fetch information for a specific product",
  "retrieve the product description",
  "can you show me details for a product",
  "I need detailed info about the product",
  "show me specifications for this product",
  "what is the info about the product",
  "list the product details",
  "give me the product name and details",
  "can I get product information",
  "show me detailed information about a product",
  "retrieve specifications for a product",
  "find the details of the selected product",
  "what is the product description",
  "fetch the detailed info for this product",
  "show me information about this product",
  "list details of a specific product",
  "get the details of this product",
  "show the product description and specifications",
  "can you retrieve product information",
  "give the product details and specifications",
  "what is the detailed info for this item",
  "get the information about this item",
  "fetch the details of the specific product",
  "show the specification for this product",
  "retrieve the description for this item",
  "list specifications for this product",
  "get the detailed description for this product",
  "what are the details for this item",
  "give me all the info about this product",
  "fetch detailed product specifications",
  "show detailed product description",
  "can I see product details by name",
  "what is the product info",
  "get the specific product details",
];

export const getProductStockDetail = [
  "show me quantity of product",
  "what is the quantity of product",
  "available stock of product",
  "how many pieces of product are left in stock",
  "how many units of product are available",
  "how many items of product do you have",
  "what is the current stock of product",
  "how many product are in stock",
  "how much stock is available for product",
  "can I know stock of product",
  "can I know quantity of product",
  "Is stock of product available",
  "Is quantity of product available",
  "can I get stock of product",
  "total stock of product",
  "total quantity of product",
  "product stock",
  "product quantity",
  "stock of product",
  "stock product",
  "quantity product",
  "quantity of product",
  "can I get quantity of product",
  "available quantity of product",
  "remaining stock of product",
  "remaining quantity of product",
  "Is product running low on stock",
  "Is product running low on quantity",
  "are there any product left in stock",
  "are there any product left in quantity",
  "Is product nearly sold out",
  "do you have enough stock for product",
  "do you have enough quantity for product",
  "Is product available in quantity",
  "how many units of product are in stock",
  "what is the stock level of product",
  "how many remaining units of product",
  "is the product out of stock",
  "is there any stock left for product",
  "can I check the stock for product",
  "how many products are available for sale",
  "how many products can be sold for product",
  "how many are available in inventory for product",
  "what is the stock status of product",
  "is the stock for product sufficient",
  "how much inventory is available for product",
  "check stock availability for product",
  "how many units of product are left in inventory",
  "is product available in large quantity",
  "how many pieces are available for product",
  "what is the stock availability for product",
  "can I order product if stock is low",
  "how many remaining product",
  "what is the total stock of product",
  "how many remaining product quantity",
  "how many remaining product stock",
  "is product stock replenished",
  "how soon will product be restocked",
  "is product in high demand, what is the stock",
  "how long will the stock for product last",
  "what is the current stock level for product",
];

export const getProductPriceDetail = [
  "what is the price of product",
  "what is the price of available product",
  "how much does product cost",
  "what is the cost of product",
  "how much is product",
  "what is the price of product",
  "how much does product sell for",
  "can you tell me the price of product",
  "how much is product right now",
  "what is the current price of product",
  "how much do I need to pay for product",
  "can I get the price of product",
  "what is the cost of product today",
  "how much for product",
  "product price",
  "what is the price of product today",
  "what is the rate of product",
  "how much is product worth",
  "can you give me the price of product",
  "what is the selling price of product",
  "what is the price for product if I want 1 unit",
  "how much is 1 unit of product",
  "how much for 1 unit of product",
  "how much for a pack of product",
  "how much is a bundle of product",
  "how much does the product in bulk cost",
  "is there a discount for product",
  "how much does product cost with discount",
  "what is the sale price of product",
  "is product available at a lower price",
  "what is the price of product on sale",
  "how much does product cost after discount",
  "what is the discounted price of product",
  "how much will product cost with a promo",
  "can I get product at a discounted price",
  "what is the price of product with the offer",
];

export const soldProductDetail = [
  "how many products are left",
  "how many sold product",
  "how much product sold",
  "what is the total quantity of products sold",
  "how many units have been sold",
  "how many items are remaining",
  "what is the remaining stock of products",
  "how much stock is left",
  "how much revenue has been generated from sold products",
  "what is the total sales value for the products sold",
  "what is the total amount of money earned from product sales",
  "how many product have been sold",
  "what is the sales quantity for product",
  "how much of product has been sold",
  "how are the sales performing for this product",
  "what is the sales trend for product",
  "how many units are sold this month",
  "how many products were sold last month",
  "how many units have been sold this week",
  "what is the total sales of products in the last quarter",
  "how many products have been sold in total",
  "what is the total number of units sold",
  "how many orders are yet to be fulfilled",
  "how many products are pending for shipment",
  "what is the status of my sold products",
  "how many products were sold in the category",
  "what is the total sales for category products",
  "sold product list",
  "sold product quantity",
];

export const lowStockProductDetail = [
    "which products are low in stock",
    "which products have low stock",
    "what products are running out of stock",
    "which products are about to be out of stock",
    "which products need restocking",
    "what products have less than quantity alert stock",
    "which products are below the minimum stock level",
    "show me low stock products",
    "which products are critically low in stock",
    "what products have the lowest stock",
    "how many products are below stock threshold",
    "which products need to be reordered",
    "which products are running low",
    "which items have low inventory",
    "what is the status of low stock products",
    "how many units of products are low in stock",
    "which products have less than the required stock",
    "show me products with low inventory",
    "which products have a stock warning",
    "which products are at risk of stockout"
  ];

  export const productCategoryActions = [
    "in which category the product belongs",
    "which category does this product belong to",
    "find category for product",
    "product category",
    "category of product",
    "show me the category of product",
    "could you tell me the category if this product",
    "get me the category of this product",
    "what category is this product",
    "tell me the category of product",
    "which category is this product",
    "what is the category of product",
  ];
  
  
 


